
# Code derived from conStruct R package vignettes:
# https://cran.r-project.org/web/packages/conStruct/vignettes/model-comparison.html
# https://cran.r-project.org/web/packages/conStruct/vignettes/visualize-results.html
rm(list = ls())

work_dir = getwd()
setwd(work_dir)

library(tidyverse)
library(conStruct)

sp.results <- as.matrix(read_table(paste0(work_dir, "/north-island-distichus-subsp/distichus-North-paleo-island-subsp_CV_sp_xval_results.txt"), col_names = TRUE))
nsp.results <- as.matrix(read_table(paste0(work_dir, "/north-island-distichus-subsp/distichus-North-paleo-island-subsp_CV_nsp_xval_results.txt"), col_names = TRUE))

# First, get the 95% confidence intervals for the spatial and nonspatial
# models over values of K (mean +/- 1.96 the standard error)

sp.CIs <- apply(sp.results,1,function(x){mean(x) + c(-1.96,1.96) * sd(x)/length(x)})
nsp.CIs <- apply(nsp.results,1,function(x){mean(x) + c(-1.96,1.96) * sd(x)/length(x)})

# Then, plot cross-validation results for K=1:3 with 8 replicates
pdf("plots/north-island-distichus-subsp-xvalidation-results.pdf")
par(mfrow=c(1,2))
plot(rowMeans(sp.results),
     pch=19,col="blue",
     ylab="Predictive Accuracy",xlab="Values of K",
     ylim=range(sp.results,nsp.results),
     main="Cross-validation Results")
    points(rowMeans(nsp.results),col="green",pch=19)
    legend("bottomright", legend =c("Spatial", "Non-spatial"),
        col = c("blue", "green"), pch = 19)
# finally, visualize results for the spatial model
#   separately with its confidence interval bars
#
# note that you could do the same with the spatial model,
#   but the confidence intervals don't really show up
#   because the differences between predictive accuracies
#   across values of K are so large.

plot(rowMeans(sp.results),
     pch=19,col="blue",
     ylab="Predictive Accuracy", xlab="Values of K",
     ylim=range(sp.CIs),
     main="Spatial Cross-validation Results")
segments(x0 = 1:nrow(sp.results),
         y0 = sp.CIs[1,],
         x1 = 1:nrow(sp.results),
         y1 = sp.CIs[2,],
         col = "blue",lwd=2)
dev.off()

# Estimate layer contributions

# Loop through output files generated by conStruct
#   runs with K=1 through 6 and calculate the
#   layer contributions for each layer in each run

layer.contributions <- matrix(NA, nrow = 5,ncol = 5)

# load the conStruct.results.Robj and data.block.Robj
#   files saved at the end of a conStruct run
load("K1_sp_conStruct.results.Robj")
load("K1_sp_data.block.Robj")

# calculate layer contributions
layer.contributions[,1] <- c(calculate.layer.contribution(conStruct.results[[1]],data.block),rep(0,4))
tmp <- conStruct.results[[1]]$MAP$admix.proportions

for(i in 2:6){
    # load the conStruct.results.Robj and data.block.Robj
    #   files saved at the end of a conStruct run
    load(sprintf("K%s_sp_conStruct.results.Robj",i))
    load(sprintf("K%s_sp_data.block.Robj",i))
    
    # match layers up across runs to keep plotting colors consistent
    #   for the same layers in different runs
    tmp.order <- match.layers.x.runs(tmp,conStruct.results[[1]]$MAP$admix.proportions)  

    # calculate layer contributions
    layer.contributions[,i] <- c(calculate.layer.contribution(conStruct.results=conStruct.results[[1]],
                                                             data.block=data.block,
                                                             layer.order=tmp.order),
                                    rep(0,5-i))
    tmp <- conStruct.results[[1]]$MAP$admix.proportions[,tmp.order]
}