
# Code derived from https://devonderaad.github.io/aph.rad/ml.species.delim/ml.species.delimitation.html

## Load R packages
library(tidyverse)
library(adegenet)
library(mclust)
library(MASS)
library(ggforce)
library(cluster)
library(factoextra)
library(gridExtra)
library(randomForest)
library(PCDimension)
library(tsne)
library(vcfR)

## Load specimen data and VCF
ind_data <- read_table("~/distichus-ddRAD/info/distichus-popmap-master.tsv", col_names=TRUE)

vcfR <- read.vcfR("distichus-brevirostris-nomissing_pruned.vcf")    # UPDATE PATH
    dim(vcfR@gt)

##  Filter out animals excluded in vcfR object
vcfR_samples <- colnames(vcfR@gt)
vcfR_samples <- gsub("(_/).*", "\\1", vcfR_samples) %>% str_replace("_/","") # a bit hacky, but this gets rid of the duplicated path names serving as individual IDs in the `vcfR` object, which is a byproduct of plink

ind_data <- ind_data[ind_data$File_path %in% vcfR_samples,]
    dim(ind_data)

    # filter out missing SNPs
    vcfR@fix<-vcfR@fix[rowSums(is.na(vcfR@gt)) == 0,]    
    vcfR@gt<-vcfR@gt[rowSums(is.na(vcfR@gt)) == 0,]
        dim(vcfR) # note: the number of SNPs after running these commands was reduced from the VCF lacking missing data generated with vcftools

    # convert vcfR object to genind and genlight objects
    data<-vcfR2genind(vcfR)
    gen<-vcfR2genlight(vcfR)

    # scale dataframe 
    data_scaled <- scaleGen(data, center=FALSE, scale=FALSE, NA.method=c("mean"), nf)
    data_scaled <- scaleGen(data, center=FALSE, scale=FALSE)

    gen@ind.names <- ind_data$Sample_ID_pop     # First, replace the individual names in the genlight object with those from the specimen information dataframe
    pop(gen) <- ind_data$PopID # Next add population identifiers

################################################################
## Perform Principal Component Analysis

    # This performs PCA on the genlight object `gen` and requires manually choosing the number of principal components to retain
    gen_pca <- glPca(gen) # I chose 6
    gen_pca_scores <- as_tibble(as.data.frame(gen_pca$scores))
    gen_pca_scores$pop <- pop(gen)

    p <- ggplot(gen_pca_scores, aes(x=PC1, y=PC2, color = gen_pca_scores$pop)) 
        p <- p + geom_point(size=2)
        p <- p + stat_ellipse(level = 0.95, size = 1)
        p <- p + geom_hline(yintercept = 0) 
        p <- p + geom_vline(xintercept = 0) 
        p <- p + theme_bw()

    p

################################################################
## Perform DAPC (discriminant analysis of principal components)

    set.seed(15)
    # This will prompt two questions to determine the number of PCs to retain (350) 
    # and the value of K to keep based on BIC scores
    grp <- find.clusters(gen, max.n.clust=30)  
    dapc1 <- dapc(gen, grp$grp, n.pca=150, n.da=5)
    # save individual cluster assignment as file
    write.table(dapc1$grp, "DAPC-group-assignments.txt", quote=F, sep="\t", col.names=F)

    # plot clusters for first two LDs
    dapc.plot.df <- as.data.frame(dapc1$ind.coord)
    write.table(dapc.plot.df, "dapc-K10-5LDs.txt", quote=F, sep="\t", col.names=TRUE) # need column header for sample name column
    
    ggplot(data=dapc.plot.df, aes(x=LD1, y=LD2, color=grp$grp))+
    geom_point(cex=3)+
    theme_classic()+
    labs(x="Linear discriminant 1",y="Linear discriminant 2")
    ggsave("LD1-LD2.pdf")

    # plot clusters for next two LDs
    ggplot(data=dapc.plot.df, aes(x=LD3, y=LD4, color=grp$grp))+
    geom_point(cex=3)+
    theme_classic()+
    labs(x="Linear discriminant 3",y="Linear discriminant 4")
    ggsave("LD3-LD4.pdf")

################################################################
## Unsupervised Random Forest 

    # convert genind scaled data into factors for randomForest
    data_conv <- as.data.frame(data_scaled)
    data_conv[is.na(data_conv)] <- ""
    data_conv[sapply(data_conv, is.integer)] <- lapply(data_conv[sapply(data_conv, is.integer)], as.factor)
    data_conv[sapply(data_conv, is.character)] <- lapply(data_conv[sapply(data_conv, is.character)], as.factor)
    nsamp <- nrow(data_conv)

    # unsupervised random forest
    set.seed(69)
    rftest <- randomForest(data_conv, ntree=5000)
