---
title: "Isolation by distance vs. Isolation by Environment"
author: "Tanner Myers"
date: "11/29/2022"
output: html_document
---

# Load libraries and R functions
```{r}
# Change below to reflect working directory
# work_dir <- getwd()
# setwd(work_dir)
setwd("/scratch/tcm0036/distichus-ddRAD/analyses/environmental-association")

rm(list = ls())

# Load R packages
library(tidyverse)
library(reshape2)
library(vcfR)
library(adegenet)
library(hierfstat)
library(sp)
library(raster)
library(rgeos)
library(rgdal)
library(adespatial)
library(RStoolbox)
library(BEDASSLE)
library(ecodist) # MRM function may be able to replace MMRR
library(gdm)
library(vegan)
library(lavaan)
library(lavaanPlot)
library(psych)

# Load functions
## Load MMRR function available from https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.kt71r
source("~/distichus-ddRAD/scripts/MMRR.R")

## Load quickMem function from Borcard et al. (2018)
## https://raw.githubusercontent.com/zdealveindy/anadat-r/master/scripts/NumEcolR2/quickMEM.R
source("~/distichus-ddRAD/scripts/quickMEM.R")
```

# Load datasets
```{r}
# Load genetic and morphological datasets and sampling info

# Load ddRADseq individual information
RAD_data <- read_table("/home/tcm0036/distichus-ddRAD/info/distichus-popmap-cleaned-master.tsv", col_names = TRUE)
## Subset dataset to include only Hispaniolan members of the distichus species group
RAD_data2 <- RAD_data %>% filter(Sample != "4481" & Sample != "10085" & Sample != "10086") %>%
    filter(!(Taxon %in% c("websteri", "marron", "caudalis", "altavelensis"))) %>%
    filter(!grepl("_rep", Sample)) %>% # Temporary, eventually I need to deal with the technical replicates in the dataset
    filter(Island %in% "Hispaniola")

snmfK9 <- read_table("/scratch/tcm0036/distichus-ddRAD/analyses/population-structure/lea/sNMF_K9_ancestry_coefficients_cluster-specimen-cleaned.tsv")
    names(snmfK9)[names(snmfK9) == "V1"] <- "Sample_ID_pop"

RAD_data2 <- inner_join(snmfK9, RAD_data2)

## Exclude individual specimens that cluster with A. brevirostris
RAD_data2 <- RAD_data2[RAD_data2$cluster != 6 & RAD_data2$cluster != 8, ]

# Load linkage-pruned VCF file with 0% missing data
vcfR <- read.vcfR("../population-structure/distichus-spgrp-no-missing-LD-pruned-informative-names.vcf")

# convert vcfR object to adegenet genind object
dat <- vcfR2genind(vcfR)
gen <- vcfR2genlight(vcfR)
```


```{r}
# Subset datasets above for distichus subspecies only
## Subset genind & genlight object to reflect individuals retained in subsetted information file
    dat2 <- dat[indNames(dat) %in% RAD_data2$Sample_ID_pop]
    ## Set population to be sampling locality
    pop(dat2) <- RAD_data2$Locality

    ## Create genlight object and subset individuals
    gen2 <- gen[gen@ind.names %in% RAD_data2$Sample_ID_pop]
    ## Set population to be sampling locality
    pop(gen2) <- RAD_data2$Locality

# A perk of this dataset is that it allows incorporation of the
# morphometric dataset from Myers et al. (2020).
# Spreadsheet with measurements available from: https://doi.org/10.5061/dryad.qfttdz0dq
morph_data <- read_csv("mmrr/Myers_2020_distichus_morphdata.csv", col_names = TRUE)
    ## Subset by traits
    morph_data <- morph_data[, c("Latitude", "Longitude", "SVL")]
```

```{r}
# Estimate distance matrices

## Geographic distance
coords <- distinct(RAD_data2[, c("Longitude", "Latitude")])
coords <- as.matrix(coords)

geog_dist <- sp::spDists(x = coords, y = coords, longlat = TRUE)

## Environmental distance

env_df <- read_csv("mmrr/raw-environmental-variables.csv", col_names = TRUE)

env_df <- inner_join(as_tibble(coords), env_df)

# Now, do the same thing, but for raw environmental variables
env_dist <- as.matrix(dist(env_df[, 3:ncol(env_df)]))

# Estimate distances between environmental variables that capture enviromental variation across Hispaniola:
# annual mean air temperature, temperature seasonality, annual precipitation amount, and precipitation seasonality
env_sub_dist <- as.matrix(dist(env_df[, c("CHELSA_bio10_01", "CHELSA_bio10_04", "CHELSA_bio10_12", "CHELSA_bio10_15")]))

## Morphological distance

```

```{r}
## Genetic distance

# Estimate pairwise Fst for genetic differentiation matrix
data <- genind2hierfstat(dat = dat2, pop = dat2@pop)
data <- as.data.frame(cbind(dat2@pop, data[, c(2:ncol(data))]))

# gen_diff2 <- pairwise.WCfst(dat = data, diploid = TRUE)
#     save(gen_diff, file = "mmrr/Fst-matrix-distichus-subsp.RData")
    load("mmrr/Fst-matrix-distichus-subsp.RData")
    ## Changes NAs to 0s
    gen_diff2[is.na(gen_diff2)] = 0

gen_dist <- gen_diff2/(1 - gen_diff2)
    class(gen_dist)
    isSymmetric(gen_dist) # Needs to be TRUE
```

##############################################################
# Multiple Matrix Regression with Randomization
```{r}
temp <- as.matrix(dist(env_df[, c(4:12)], method = "euclidean"))
precip <- as.matrix(dist(env_df[, c(13:18)], method = "euclidean"))
veg <- as.matrix(dist(env_df[, c(19:22)], method = "euclidean"))

# Run MMRR using raw ecological variables
xvars <- list(geo = geog_dist, temp = temp, precip = precip, veg = veg)
MMRR(gen_dist, xvars, nperm = 1000)

# Run MMRR using raw ecological variables without precip
xvars <- list(geo = geog_dist, temp = temp, veg = veg)
MMRR(gen_dist, xvars, nperm = 1000)

# Run MMRR using raw ecological variables without veg
xvars <- list(geo = geog_dist, temp = temp, precip = precip)
MMRR(gen_dist, xvars, nperm = 1000)

# Only IBD
xvars <- list(geography = geog_dist)
MMRR(gen_dist, xvars, nperm = 1000)
```


############################################################
# Structural equation modeling (SEM)
```{r}
# SEM

all_data <- inner_join(RAD_data2, env_df)

latlong <- SpatialPoints(RAD_data2[, c("Longitude", "Latitude")], proj4string = CRS("+proj=longlat"))

distichus_xy <- as.data.frame(spTransform(latlong, CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")))

# Create distance matrices from geographic distance and environmental variables
    ## `melt` is used to transform distance matrices into dataframes and I am
    ## keeping only the third column with the distance estimates
geo.dist <- melt(base::scale(dist(distichus_xy, method = "euclidean")))[, 3]
env.dist.1 <- melt(base::scale(dist(all_data$CHELSA_bio10_01, method = "euclidean")))[, 3]
env.dist.2 <- melt(base::scale(dist(all_data$CHELSA_bio10_02, method = "euclidean")))[, 3]
env.dist.3 <- melt(base::scale(dist(all_data$CHELSA_bio10_03, method = "euclidean")))[, 3]
env.dist.4 <- melt(base::scale(dist(all_data$CHELSA_bio10_04, method = "euclidean")))[, 3]
env.dist.5 <- melt(base::scale(dist(all_data$CHELSA_bio10_05, method = "euclidean")))[, 3]
env.dist.6 <- melt(base::scale(dist(all_data$CHELSA_bio10_06, method = "euclidean")))[, 3]
env.dist.7 <- melt(base::scale(dist(all_data$CHELSA_bio10_07, method = "euclidean")))[, 3]
env.dist.8 <- melt(base::scale(dist(all_data$CHELSA_bio10_10, method = "euclidean")))[, 3]
env.dist.9 <- melt(base::scale(dist(all_data$CHELSA_bio10_11, method = "euclidean")))[, 3]
env.dist.10 <- melt(base::scale(dist(all_data$CHELSA_bio10_12, method = "euclidean")))[, 3]
env.dist.11 <- melt(base::scale(dist(all_data$CHELSA_bio10_13, method = "euclidean")))[, 3]
env.dist.12 <- melt(base::scale(dist(all_data$CHELSA_bio10_14, method = "euclidean")))[, 3]
env.dist.13 <- melt(base::scale(dist(all_data$CHELSA_bio10_15, method = "euclidean")))[, 3]
env.dist.14 <- melt(base::scale(dist(all_data$CHELSA_bio10_16, method = "euclidean")))[, 3]
env.dist.15 <- melt(base::scale(dist(all_data$CHELSA_bio10_17, method = "euclidean")))[, 3]
env.dist.16 <- melt(base::scale(dist(all_data$SRTM_elevation_1km, method = "euclidean")))[, 3]
env.dist.17 <- melt(base::scale(dist(all_data$march_EVI_mean, method = "euclidean")))[, 3]
env.dist.18 <- melt(base::scale(dist(all_data$march_NDVI_mean, method = "euclidean")))[, 3]
env.dist.19 <- melt(base::scale(dist(all_data$may_EVI_mean, method = "euclidean")))[, 3]
env.dist.20 <- melt(base::scale(dist(all_data$may_NDVI_mean, method = "euclidean")))[, 3]

# Create distance matrix from genetic data
gen.dist <- melt(base::scale(dist(gen2, method = "euclidean")))
    colnames(gen.dist) <- c("Specimen1", "Specimen2", "gen.dist")

# Now, merge all distance matrices into a single dataframe
full <- data.frame(gen.dist, env.dist.1, env.dist.2, env.dist.3, env.dist.4, env.dist.5, env.dist.6,
                env.dist.7, env.dist.8, env.dist.9, env.dist.10, env.dist.11, env.dist.12, env.dist.13,
                env.dist.14, env.dist.15, env.dist.16, env.dist.17, env.dist.18, env.dist.19, env.dist.20,
                geo.dist)

## Define model framework for SEM
    ## =~ operator defines latent variables
    ## ~~ variance/covariance operator
    ## This model specifies genetic distance as as the dependent variable
    ## of two latent variables: environmental dissimilarity and geographic
    ## distance
## Both latent variables
model_all <- '
    env =~ env.dist.1+env.dist.2+env.dist.3+env.dist.4+env.dist.5+env.dist.6+env.dist.7+env.dist.8+env.dist.9+env.dist.10+env.dist.11+env.dist.12+env.dist.13+env.dist.14+env.dist.15+env.dist.16+env.dist.17+env.dist.18+env.dist.19+env.dist.20
    geo =~ geo.dist

    gen.dist ~ env + geo
    geo ~~ env
    env ~~ env
    geo ~~ geo
'

fit_all <-  sem(model_all, data = full, estimator = "MLR", se = "robust.huber.white")
s_all <- summary(fit_all, standardized = TRUE, fit.measures = TRUE, rsquare = TRUE)
p_all <- parameterEstimates(fit_all)

png("sem/full-model-fit.png")
lavaanPlot(model = fit_all, node_options = list(shape = "box", fontname = "Helvetica"), coefs = TRUE, edge_options = list(color = "grey"))
dev.off()

## Geography only
model_geo <- '
    geo =~ geo.dist

    gen.dist ~ geo

    geo ~~ geo
'
fit_geo <- sem(model_geo, data = full, estimator = "MLR", se = "robust.huber.white")
s_geo <- summary(fit_geo, standardized = TRUE, fit.measures = TRUE, rsquare = TRUE)
p_geo <- parameterEstimates(fit_geo)

model_env <- '
    env =~ env.dist.1+env.dist.2+env.dist.3+env.dist.4+env.dist.5+env.dist.6+env.dist.7+env.dist.8+env.dist.9+env.dist.10+env.dist.11+env.dist.12+env.dist.13+env.dist.14+env.dist.15+env.dist.16+env.dist.17+env.dist.18+env.dist.19+env.dist.20

    gen.dist ~ env
    env ~~ env
'

fit_env <- sem(model_env, data = full, estimator = "MLR", se = "robust.huber.white")
s_env <- summary(fit_env, standardized = TRUE, fit.measures = TRUE, rsquare = TRUE)
p_env <- parameterEstimates(fit_env)

anova(fit_all, fit_geo, fit_env)
```

############################################################
# RDA
```{r}
# dbMEM
#dbmem.1 <- quickMEM(dat3@tab, distichus_xy, perm.max = 999)
    load("rda/dbMEM_distichus-subspecies.RData")

dbmem_all <- dbmem(distichus_xy)

dbmem_keep <- dbmem_all[, c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 20, 21, 24)]

png("rda/sig_dbmems.png", width = 10, height = 16, units="in", res=600)
    par(mfrow = c(4, 5))
    for(i in 1:ncol(dbmem.1$dbMEM_red_model)){
        sr.value(distichus_xy, dbmem.1$dbMEM_red_model[,i], sub = names(dbmem.1$dbMEM_red_model)[i])
    }
dev.off()

rda_distichus_1 <- rda(dat2@tab ~., data = all_data[, 22:ncol(all_data)], scale = TRUE)
rda_distichus_1r2 <- RsquareAdj(rda_distichus_1)
    summary(rda_distichus_1)$concont

vif.cca(rda_distichus_1)

signif.rda.1 <- anova.cca(rda_distichus_1)

levels(all_data$cluster) <- c("ignigularis", "east dominicensis", "South paleo-island", "properus", "west dominicensis", "ravitergum")
clust <- all_data$cluster
bg <- c("#cf5d34", "#634102", "#993cc8", "gray80", "#c6b89c", "#fddc1f")

#pdf("rda/rda-distichus-subsp-full-plot.pdf")
pdf("rda/rda-distichus-chrom2-full-plot-simple.pdf")
    plot(rda_distichus_1, type = "n", scaling = 3)
    #points(rda_distichus_1, display = "species", pch = 20, cex = 0.7, col = "gray32", scaling = 3, choices = c(1, 2)) # SNPs in this case
    points(rda_distichus_1, display = "sites", pch = 21, cex = 1.3, col = "gray32", scaling = 3, bg = bg[as.factor(clust)], choices = c(1, 2)) # lizards
    #text(rda_distichus_1, scaling = 3, display = "bp", col = "#0868ac", cex = 1) # predictor variables
    legend("topright", legend = levels(clust), bty = "n", col = "gray32", pch = 21, cex = 1, pt.bg = bg)
dev.off()

######## Forward selection of environmental variables

#rda_distichus_fwd <- forward.sel(dat2@tab, all_data[, 22:ncol(all_data)], adjR2thresh = rda_distichus_1r2, nperm = 9999, alpha = 0.01)
    load("rda/forward-selection-unconstrained-rda.RData")
## Forward selection identified the following variables:
#         variables order         R2      R2Cum   AdjR2Cum         F pvalue
# 1 CHELSA_bio10_15    14 0.06776521 0.06776521 0.06305695 14.392845  1e-04  ---  Precipitation seasonality
# 2 CHELSA_bio10_04     5 0.05053607 0.11830128 0.10935002 11.291393  1e-04  ---  Temperature seasonality
# 3   may_NDVI_mean    20 0.03130939 0.14961067 0.13659451  7.216272  1e-04  ---  Wet season NDVI
# 4 CHELSA_bio10_03     4 0.03109568 0.18070635 0.16390033  7.401080  1e-04  ---  Isothermality
# 5 CHELSA_bio10_07     8 0.03639532 0.21710167 0.19692388  9.018657  1e-04  ---  Annual air temperature range
# 6 CHELSA_bio10_02     3 0.01841968 0.23552135 0.21175518  4.650226  1e-04  ---  Mean diurnal air temperature range

variables <- c("CHELSA_bio10_15", "CHELSA_bio10_04", "may_NDVI_mean", "CHELSA_bio10_03", "CHELSA_bio10_07", "CHELSA_bio10_02")

good_env <- all_data[, variables]

rda_distichus_2 <- rda(dat2@tab ~., data = good_env, scale = TRUE)
rda_distichus_2r2 <- RsquareAdj(rda_distichus_2)
    summary(rda_distichus_2)$concont

vif.cca(rda_distichus_2)
signif.rda.2 <- anova.cca(rda_distichus_2)

levels(all_data$cluster) <- c("ignigularis", "east dominicensis", "South paleo-island", "properus", "west dominicensis", "ravitergum")
clust <- all_data$cluster
bg <- c("#cf5d34", "#634102", "#993cc8", "gray80", "#c6b89c", "#fddc1f")

pdf("rda/rda-distichus-subsp-var-subset-plot.pdf")
    plot(rda_distichus_2, type = "n", scaling = 3)
    points(rda_distichus_2, display = "species", pch = 20, cex = 0.7, col = "gray32", scaling = 3, choices = c(1, 2)) # SNPs in this case
    points(rda_distichus_2, display = "sites", pch = 21, cex = 1.3, col = "gray32", scaling = 3, bg = bg[as.factor(clust)], choices = c(1, 2)) # lizards
    text(rda_distichus_2, scaling = 3, display = "bp", col = "#0868ac", cex = 1) # predictor variables
    legend("bottomright", legend = levels(clust), bty = "n", col = "gray32", pch = 21, cex = 1, pt.bg = bg)
dev.off()

######## Variance partitioning

vp <- varpart(dat2@tab, good_env, dbmem.1$dbMEM_red_model)
png("rda/venn_partitions.png", width = 6, height = 6, units = "in", res = 600)
    plot(vp, bg = c("red", "blue"), digits = 1, Xnames = c('Env', 'Space'))
dev.off()

anova(rda(dat2@tab, good_env, dbmem.1$dbMEM_red_model))

anova(rda(dat2@tab, dbmem.1$dbMEM_red_model, good_env))

######## Constrained on Space
rda_distichus_cond <- rda(dat2@tab, good_env, dbmem.1$dbMEM_red_model)
    rda_distichus_cond_r2 <- RsquareAdj(rda_distichus_cond)$r.squared
    summary(rda_distichus_cond)$concont

null_model <- rda(dat2@tab ~ Condition(as.matrix(dbmem.1$dbMEM_red_model)), data = all_data[, 22:ncol(all_data)])

full_model <- rda(dat2@tab ~ . + Condition(as.matrix(dbmem.1$dbMEM_red_model)), data = all_data[, 22:ncol(all_data)])

ordi <- ordistep(null_model, scope = formula(full_model), direction = "forward")
    load("rda/constrained-variable-selection.RData")
## This selects too many variables? 18 of 20 are left at the end

#cond_envs <- data.frame(all_data$CHELSA_bio10_15)
```

# Generalized dissimilarity modeling (GDM)
```{r}
setwd("gdm")
sitespecies <- data.frame(all_data$Longitude, all_data$Latitude, dat2@tab)
sitespecies$site <- rownames(dat2@tab)
pred_env <- good_env
pred_env$site <- rownames(dat2@tab)
pred_env <- data.frame(pred_env, all_data$Longitude, all_data$Latitude)
    no_env <- pred_env[, c(7, 8, 9)]

# Format data for GDM
gdm_tab <- formatsitepair(sitespecies, bioFormat = 1, XColumn = "all_data.Longitude", YColumn = "all_data.Latitude", predData = pred_env, siteColumn = "site")
gdm_tab_geog <- formatsitepair(sitespecies, bioFormat = 1, XColumn = "all_data.Longitude", YColumn = "all_data.Latitude", predData = no_env, siteColumn = "site")

# Run GDM
gdm_e <- gdm(gdm_tab, geo = FALSE)
gdm_eg <- gdm(gdm_tab, geo = TRUE)
gdm_g <- gdm(gdm_tab_geog, geo = TRUE)

# Run GDM with variable selection
gdm_1_imp <- gdm.varImp(gdm_tab, geo = TRUE, nPerm = 100, cores = 12, parallel = TRUE, outFile = "gdm.1.imp")
gdm_1_imp_full <- gdm.varImp(gdm_tab, geo = TRUE, nPerm = 999, cores = 12, parallel = TRUE, outFile = "gdm.1.full.imp")
gdm_1_imp_full_nogeo <- gdm.varImp(gdm_tab, geo = FALSE, nPerm = 999, cores = 12, parallel = TRUE, outFile = "gdm.1.nogeo.imp")

pred_env2 <- subset(pred_env, select = -c(CHELSA_bio10_02, CHELSA_bio10_03, CHELSA_bio10_04, CHELSA_bio10_07))
gdm_tab2 <- formatsitepair(sitespecies, bioFormat=1, XColumn = "all_data.Longitude", YColumn = "all_data.Latitude", predData = pred_env2, siteColumn = "site")

gdm(gdm_tab2, geo = TRUE)
```